### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lightweight** [ButterCMS/meteor-cms-blog#1]
Just wondering under what license you're making your code available? It's "all rights reserved" totally restrictive copyright by default...

**Comment by rogerjin12** [comment]
@lightweight Thanks for bringing this to our attention! We'll add a CC license – so feel free to use, repurpose, share this code as you'd like.

**Comment by lightweight** [comment]
I think you'll want a code license, like GPL or MIT... CC licenses are for creative works.

**Comment by rogerjin12** [comment]
@lightweight Thanks, will look into it

**Comment by lightweight** [comment]
If you create a file called LICENSE and then when you edit it in the Github interface, it'll offer you the option to pick from a series of license templates...

**Comment by rogerjin12** [comment]
Wow, thats great! Thanks for the tip. We were looking at Github's https://choosealicense.com but it didn't have one that seemed like what we were looking for (use without attribution).
